# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31cad413b42651d463ad7f126f41ff501e8141f2a9154bf3bab6e9edf18b55ec0fe18ac4e00ee69d84e81ffdcca752cc0d772baea4c24e712f54c17fd2a764fb

test:
  secret_key_base: 4f7793af61a1b5334892f8b86b62cf0577f66bcc8b67c46a507df76c92abd0be7e8d1c9d9e3203b6fc91cc98a253bddf08433fe591774190c372d1a2ee6aa235

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
